version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring:/etc/prometheus/monitoring:ro
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
    ports:
      - '3000:3000'
    restart: unless-stopped

# Optionally you can add node exporter or pushgateway services
  vault:
    image: "vault:1.15"
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    command: "server -dev -dev-root-token-id=root"
    ports:
      - "8200:8200"
    volumes:
      - ./monitoring/vault:/vault/file
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mobil-redis
    ports:
      - '6379:6379'
    restart: unless-stopped
